//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int id { get; set; }
        public string itemCategory { get; set; }
        public string itemMeasurement { get; set; }
        public string itemName { get; set; }
        public string itemCode { get; set; }
        public string itemQuantity { get; set; }
        public string itemPrice { get; set; }
        public string itemSupplier { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
    }
}
